Wdp200801 93
PatrykBulaKodilla/WDP-2008-01 pull request #61
Opened 2020-08-23 19:23 UTC by lukas1474

2020-08-23 20:14 UTC, PatrykBulaKodilla requested changes
2 poprawki.
Po ich poprawieniu dam approve.

2020-08-23 20:14 UTC, PatrykBulaKodilla commented on src/components/features/ComprasionBox/ComprasionBox.js
> +            {compare.map(products => (
do każdego ProductBox wpada jeden produkt. Nazwa products jest myląca, bo sugeruje, że produktów jest wiele.

2020-08-23 20:14 UTC, PatrykBulaKodilla commented on src/redux/productsRedux.js
> +// export const  getProduct =({ products}) =>
Nie śmiecimy. Komentarze do kosza.

2020-08-23 21:09 UTC, lukas1474 commented
Poprawione.

2020-08-24 15:27 UTC, PatrykBulaKodilla approved these changes

2020-08-24 15:27 UTC, merged